export const ADD_TO_CART = 'ADD_TO_CART';
export const BUY_NOW = 'BUY_NOW';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const GET_TOTALS = "GET_TOTALS";

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const WISHLIST_BUY_NOW = 'WISHLIST_BUY_NOW';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const WISHLIST_INCREASE_QUANTITY = 'WISHLIST_INCREASE_QUANTITY';
export const WISHLIST_DECREASE_QUANTITY = 'WISHLIST_DECREASE_QUANTITY';
export const WISHLIST_GET_TOTALS = "WISHLIST_GET_TOTALS";



